# Generated by Django 6.0.5 on 2026-06-03 02:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('set_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint (NM)'), ('LP', 'Lightly Played (LP)'), ('MP', 'Moderately Played (MP)'), ('HP', 'Heavily Played (HP)'), ('DMG', 'Damaged (DMG)')], default='NM', max_length=3)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('offer_percent', models.DecimalField(decimal_places=2, default=Decimal('0.70'), max_digits=4)),
                ('offer_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('buylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buylists.buylist')),
            ],
            options={
                'ordering': ['card_name'],
            },
        ),
        migrations.AddField(
            model_name='buylist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buylists', to='buylists.customer'),
        ),
    ]
