# Generated by Django 6.0.5 on 2026-06-03 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylists', '0008_buylist_payment_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buylist',
            name='unlock_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buylist',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buylist',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buylists_unlocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
