# Generated by Django 6.0.5 on 2026-06-03 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylists', '0009_buylist_item_unlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuylistActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buylist_created', 'Buylist created'), ('item_added', 'Item added'), ('item_updated', 'Item updated'), ('item_deleted', 'Item deleted'), ('status_changed', 'Status changed'), ('offer_printed', 'Offer printed'), ('csv_exported', 'CSV exported'), ('payment_recorded', 'Payment recorded'), ('override_added', 'Override added')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='buylists.buylist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buylist_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'buylist activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
